name: Build on push

on:
  push:
  pull_request:

jobs:
  build:
    name: Build Package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: npm run build
